### ISSUE TITLE
Webpack Error Import MapLibreLayer

### ISSUE THREAD

**Issue by AlvaroCodes** [geoblocks/ol-maplibre-layer#191]
Error https://github.com/openlayers/ol-webpack + ol-maplibre-layer

export 'MapLibreLayer' (imported as 'MapLibreLayer') was not found in '@geoblocks/ol-maplibre-layer' (module has no exports)

ERROR in ./node_modules/@geoblocks/ol-maplibre-layer/lib/index.js 1:0-59
Module not found: Error: Can't resolve './MapLibreLayer' in 'x/ol-webpack/node_modules/@geoblocks/ol-maplibre-layer/lib'
Did you mean 'MapLibreLayer.js'?
BREAKING CHANGE: The request './MapLibreLayer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./main.js 2:0-61 5:15-28

ERROR in ./node_modules/@geoblocks/ol-maplibre-layer/lib/index.js 2:0-75
Module not found: Error: Can't resolve './MapLibreLayerRenderer' in 'x/ol-webpack/node_modules/@geoblocks/ol-maplibre-layer/lib'
Did you mean 'MapLibreLayerRenderer.js'?
BREAKING CHANGE: The request './MapLibreLayerRenderer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./main.js 2:0-61 5:15-28

ERROR in ./node_modules/@geoblocks/ol-maplibre-layer/lib/index.js 3:0-79
Module not found: Error: Can't resolve './getMapLibreAttributions' in 'x/ol-webpack/node_modules/@geoblocks/ol-maplibre-layer/lib'
Did you mean 'getMapLibreAttributions.js'?
BREAKING CHANGE: The request './getMapLibreAttributions' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by taulinger** [comment]
@AlvaroCodes  This should be fixed with #187, but it has not been released yet.
@fredj Can we have a new release, please?

**Comment by fredj** [comment]
Same issue with the CI: https://github.com/geoblocks/ol-maplibre-layer/actions/runs/12006297255/job/33464555856

I will look at it today

**Comment by quantenschaum** [comment]
I got it. I followed some older instructions, I needed to import it with `{}` like 

`import {MapLibreLayer} from '@geoblocks/ol-maplibre-layer';`

**Comment by fredj** [comment]
Good catch @quantenschaum, I've updated the readme.

I've published a new version: https://www.npmjs.com/package/@geoblocks/ol-maplibre-layer/v/1.0.2

**Comment by fredj** [comment]
There's still an issue with newer version of parcel, I will try to fix it this week
